import Mathlib.Analysis.Normed.Lp.lpSpace
import Mathlib.Analysis.Normed.Module.TransferInstance

/-!
# `def` vs `structure`: two ways to "make a new type from ℝ"

Both idioms produce something that typeclass search treats as distinct from ℝ.
But they differ on FIVE axes: kernel identity, constructor syntax,
projection syntax, typeclass inheritance, and `rfl` behavior.

We'll use the same running example — "ℝ with a weighted norm" — built both ways.
-/

set_option linter.unusedVariables false

------------------------------------------------------------------------
-- Version A: `def` synonym (opaque to typeclass search, defeq to ℝ)
------------------------------------------------------------------------

def RDef (ν : ℝ) (n : ℕ) := ℝ

namespace RDef

-- "Constructor" and "projector" — both are the identity, manually written.
def ofReal (x : ℝ)      : RDef ν n := x
def toReal (x : RDef ν n) : ℝ       := x

-- Kernel sees RDef ν n as literally ℝ:
example : RDef 2 3 = ℝ := rfl              -- passes by definitional unfolding

-- Typeclass search does NOT see through `def` unless told to
-- (it treats `RDef ν n` as distinct). We INHERIT what we want:
instance : Add     (RDef ν n) := inferInstanceAs (Add ℝ)
instance : Zero    (RDef ν n) := inferInstanceAs (Zero ℝ)
instance : AddCommGroup (RDef ν n) := inferInstanceAs (AddCommGroup ℝ)

-- And OVERRIDE what we want to change:
noncomputable instance : Norm (RDef ν n) where
  norm x := |toReal x| * ν ^ n

-- Check: addition works via inherited instance, norm is the overridden one.
example (x y : RDef ν n) : RDef ν n := x + y           -- uses inherited Add
example (x : RDef ν n) : ‖x‖ = |toReal x| * ν ^ n := rfl  -- uses overridden Norm

end RDef

------------------------------------------------------------------------
-- Version B: `structure` wrapper (fresh inductive type, not defeq to ℝ)
------------------------------------------------------------------------

structure RStruct (ν : ℝ) (n : ℕ) where
  toReal : ℝ

namespace RStruct

-- Auto-generated by Lean:
--   RStruct.mk     : ℝ → RStruct ν n
--   RStruct.toReal : RStruct ν n → ℝ

-- Kernel sees RStruct ν n as DIFFERENT from ℝ:
-- example : RStruct 2 3 = ℝ := rfl              -- ERROR: not defeq

-- Nothing is inherited automatically. We have to BUILD every instance:
instance : Add (RStruct ν n) where
  add x y := ⟨x.toReal + y.toReal⟩

instance : Zero (RStruct ν n) where
  zero := ⟨0⟩

noncomputable instance : Norm (RStruct ν n) where
  norm x := |x.toReal| * ν ^ n

-- `structure`-level rewriting needs explicit projection:
example (x y : RStruct ν n) : (x + y).toReal = x.toReal + y.toReal := rfl
example (x : RStruct ν n)    : ‖x‖ = |x.toReal| * ν ^ n           := rfl

end RStruct

------------------------------------------------------------------------
-- The five differences, side by side
------------------------------------------------------------------------

/-!
### (1) Kernel identity

  `def`       — RDef ν n    IS ℝ at kernel level (`rfl` passes).
  `structure` — RStruct ν n is a NEW inductive type, not defeq to ℝ.
-/

example : RDef 2 3 = ℝ := rfl
-- example : RStruct 2 3 = ℝ := rfl  -- would fail

/-!
### (2) Constructor syntax

  `def`       — write `ofReal : ℝ → RDef ν n := id` manually.
                `RDef.ofReal x` is literally the identity.
  `structure` — Lean generates `RStruct.mk : ℝ → RStruct ν n` for you.
                `⟨x⟩` and `{ toReal := x }` syntax both work.
-/

example : RDef    ν n := (RDef.ofReal   (3 : ℝ) : RDef ν n)
example : RStruct ν n := (RStruct.mk    (3 : ℝ) : RStruct ν n)
example : RStruct ν n := ⟨(3 : ℝ)⟩
example : RStruct ν n := { toReal := 3 }

/-!
### (3) Projection syntax

  `def`       — `RDef.toReal x` is the identity (no real work).
  `structure` — `x.toReal` is a real projection; Lean generates it.

Both look the same at use sites thanks to dot notation.
-/

example (x : RDef    ν n) : ℝ := x.toReal         -- defeq to `x` itself
example (x : RStruct ν n) : ℝ := x.toReal         -- actual projection

/-!
### (4) Typeclass inheritance

  `def`       — inherit with `inferInstanceAs (C ℝ)`: one line per instance.
                Underlying ops (+, *) ARE ℝ's ops, no wrapping.
  `structure` — build each instance explicitly. `x + y` must unwrap via
                `.toReal`, add, then re-wrap. More boilerplate, but total control.

`def` wins when you want to "inherit most things, change a few."
`structure` wins when you want NO automatic carryover (e.g., `lpOneAlg`,
which rebuilds Ring/Algebra/NormedAlgebra from scratch for Banach algebra
semantics distinct from `lp`).
-/

-- def: addition IS ℝ addition, no wrapping
example (x y : RDef ν n) :
    RDef.toReal (x + y) = RDef.toReal x + RDef.toReal y := rfl   -- rfl! same ops

-- structure: addition UNWRAPS, adds, RE-WRAPS
example (x y : RStruct ν n) :
    (x + y).toReal = x.toReal + y.toReal := rfl                   -- rfl, but via mk/.toReal

/-!
### (5) `rfl` and simp behavior

  `def`       — many things are `rfl` because ops pass through the identity.
                BUT: simp sees `RDef.toReal x` and DOESN'T unfold (since
                `def` is opaque to reducibility by default). You add
                `@[simp]` lemmas like `RDef.toReal_add : (x + y).toReal = ...`.
  `structure` — projections reduce through the constructor (`.mk _ |>.toReal = _`)
                but arithmetic lemmas still need to be stated explicitly.
-/

-- `def` case: even though ops are defeq to ℝ's, simp won't see through the opaque name:
@[simp] theorem RDef.toReal_add (x y : RDef ν n) :
    (x + y).toReal = x.toReal + y.toReal := rfl

-- `structure` case: the mk/toReal round-trip is definitional,
-- but you still write @[simp] lemmas for readability:
@[simp] theorem RStruct.toReal_add (x y : RStruct ν n) :
    (x + y).toReal = x.toReal + y.toReal := rfl

------------------------------------------------------------------------
-- The decision table
------------------------------------------------------------------------

/-!
                             `def S := T`           `structure S where t : T`
                             ------------           --------------------------
Kernel identity              S ≡ T (defeq)          S is a fresh type
Fields                       no fields              one projection per field
Constructor                  write ofT manually     auto `.mk`
Projector                    write toT manually     auto by field name
`abbrev` alternative         reducible (bad!)       — (n/a)
Typeclass search sees S as   a distinct name        a distinct inductive
Inherit parent instance      `inferInstanceAs`      must define manually
Underlying ops               exactly T's ops        wrap/unwrap around T's ops
Typical use                  override specific      bundle new data or
                             typeclasses only       completely rebuild
                             (Norm, Mul, etc.)      algebraic hierarchy

Examples in this project:

  ScaledReal     (def)       — override Norm on ℝ, keep arithmetic.
  WeightedScalar (def)       — same, parameterized.
  lpOneAlg       (structure) — wrap `lp E 1`, rebuild Ring/Algebra from scratch.
  Point3 extends Point       — structure-to-structure inheritance via `extends`.

RULE OF THUMB:
  • "I want this to BEHAVE like T with different typeclasses" → `def`.
  • "I want this to BE a new object that happens to wrap T" → `structure`.
-/

------------------------------------------------------------------------
-- One more concrete contrast: building a `NormedAddCommGroup` both ways
------------------------------------------------------------------------

-- `def` way: inherit AddCommGroup, transfer NormedAddCommGroup via the Equiv
-- (still clean because the equiv is `id`):

-- `structure` way (e.g. lpOneAlg): use `Equiv.normedAddCommGroup` on the
-- wrapper equiv — exactly what we showed in `structure_explained.lean`.

-- Both ultimately produce a `NormedAddCommGroup S` instance. The difference
-- is HOW MUCH of the surrounding algebra comes free vs. needs manual setup.
