name = "RadiiPolynomial"
version = "0.1.0"
defaultTargets = ["RadiiPolynomial"]

[[lean_lib]]
name = "RadiiPolynomial"

[[require]]
name = "checkdecls"
git = "https://github.com/PatrickMassot/checkdecls.git"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "81a5d257c8e410db227a6665ed08f64fea08e997"

[[require]]
name = "LeanCert"
path = "/Users/ilpreterosso/VSCode/Lean/LeanCert/leancert-main"
