import RadiiPolynomial.Analysis.SequenceSpace.WeightedL1.UniversalProperty
import RadiiPolynomial.Analysis.SequenceSpace.Geometric.Evaluation

/-!
# The geometric ℓ¹ algebra is generated by `e₁`: the `aeval` API

Over the geometric weight `n ↦ νⁿ` on `ℕ`, the weighted ℓ¹ algebra
`lpOneAlg ℕ (geomFiber 𝕜 ν)` is the algebra of one generator `e₁ = single 1 1`
under the growth constraint `‖e₁ⁿ‖ = νⁿ` (`norm_gen_pow`, from `single_pow` +
`geomFiber_weight`): `ν` is the spectral radius of `e₁`. Its continuous
algebra homomorphisms into a Banach algebra `B` are exactly the power-series
evaluations at elements of power growth `‖xⁿ‖ ≤ C νⁿ` — three faces and a
converse:

* introduction — `lpOneAlg.geomAeval 𝕜 ν x C hx : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B`,
  the evaluation `a ↦ ∑' n, aₙ • xⁿ` (`geomAeval_apply`), with the pointwise
  bound `norm_geomAeval_apply_le : ‖geomAeval 𝕜 ν x C hx a‖ ≤ C * ‖a‖`; the
  hypothesis is power growth, not `‖x‖ ≤ ν` — the latter is the `C = 1` case
  `geomAeval_of_norm_le` (in a `NormOneClass` target);
* uniqueness — `lpOneAlg.geomAlgHom_ext`: two continuous algebra homomorphisms
  agreeing on `e₁` are equal;
* computation — `@[simp] geomAeval_gen : geomAeval 𝕜 ν x C hx (single 1 1) = x`
  (and `geomAeval_single` on every `eₙ`);
* completeness — `lpOneAlg.eq_geomAeval_gen`: every continuous `𝕜`-algebra
  homomorphism out of the algebra is evaluation at the image of the generator,
  at the growth constant `‖φ.toContinuousLinearMap‖` (`norm_gen_pow_le`);
  `exists_eq_geomAeval` is the existential form;
* the gate — `lpOneAlg.norm_gen_le`: when the norm of the target is
  multiplicative (`NormMulClass`), the image of the generator lies in the
  closed disc of radius `ν`, `‖φ e₁‖ ≤ ν`. This is the half of the character
  classification that `eq_geomAeval_gen` does not give.

The scalar field is generic: `geomFiber 𝕜 ν` is `WeightedScalar 𝕜 (fun n => νⁿ)`,
and `ScaledReal ν = geomFiber ℝ ν` definitionally, so `l1Weighted ν` is the
`𝕜 = ℝ` instance. The `l1Weighted.aeval` block restates the faces on it, and
`l1Weighted.aeval_eq_evalContinuousAlgHom` identifies the library's pointwise
evaluation `evalContinuousAlgHom z hz` (Evaluation.lean, built by Mertens) with
`aeval_of_norm_le ν z hz` — by uniqueness alone, since both send `e₁` to `z`.

Main declarations:
* `geomFiber`, `geomFiber_weight`
* `lpOneAlg.geomAeval`, `geomAeval_apply`, `geomAeval_single`, `geomAeval_gen`,
  `norm_geomAeval_apply_le`, `geomAeval_of_norm_le`
* `lpOneAlg.gen_pow_eq_single`, `norm_gen_pow`, `geomAlgHom_ext`
* `lpOneAlg.norm_gen_pow_le`, `eq_geomAeval_gen`, `exists_eq_geomAeval`
* `lpOneAlg.norm_gen_le`, `l1Weighted.norm_gen_le`
* `l1Weighted.aeval`, `aeval_gen`, `algHom_ext`, `eq_aeval_gen`,
  `single_eq_lpOneAlg_single`, `evalContinuousAlgHom_gen`,
  `aeval_eq_evalContinuousAlgHom`
-/

noncomputable section

namespace RadiiPolynomial

/-- The geometric fiber over a normed field `𝕜`: `𝕜` with norm `‖x‖ νⁿ` at
index `n`. `ScaledReal ν = geomFiber ℝ ν` definitionally. -/
abbrev geomFiber (𝕜 : Type*) [NormedField 𝕜] (ν : PosReal) :=
  WeightedScalar 𝕜 (fun n : ℕ => (ν : ℝ) ^ n)

section Fiber

variable {𝕜 : Type*} [NormedField 𝕜] (ν : PosReal)

/-- The weight of the geometric fiber at `n` is `νⁿ`. -/
theorem geomFiber_weight (n : ℕ) :
    ‖lpAlgRingData.ofReal (E := geomFiber 𝕜 ν) n (1 : 𝕜)‖ = (ν : ℝ) ^ n := by
  rw [show lpAlgRingData.ofReal (E := geomFiber 𝕜 ν) n (1 : 𝕜)
      = WeightedScalar.ofReal 1 from rfl, WeightedScalar.norm_ofReal,
    norm_one, one_mul]

example : ScaledReal ν = geomFiber ℝ ν := rfl

example : l1Weighted ν = lpOneAlg ℕ (geomFiber ℝ ν) := rfl

end Fiber

namespace lpOneAlg

/-! ### Introduction: evaluation at an element of power growth -/

section Aeval

variable (𝕜 : Type*) [NormedField 𝕜] (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormedAlgebra 𝕜 B] [CompleteSpace B]

omit [NormedAlgebra 𝕜 B] [CompleteSpace B] in
/-- Power growth `‖xⁿ‖ ≤ C νⁿ` is domination by the geometric weight. -/
theorem pow_le_geomFiber_weight (x : B) (C : ℝ)
    (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n) (n : ℕ) :
    ‖x ^ n‖ ≤ C * ‖lpAlgRingData.ofReal (E := geomFiber 𝕜 ν) n (1 : 𝕜)‖ := by
  rw [geomFiber_weight]
  exact hx n

/-- **Evaluation at an element of power growth** (introduction face): for
`x : B` with `‖xⁿ‖ ≤ C νⁿ`, the continuous algebra homomorphism
`a ↦ ∑' n, aₙ • xⁿ` out of the geometric ℓ¹ algebra. -/
def geomAeval (x : B) (C : ℝ) (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n) :
    lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B :=
  liftAlgHom (fun n => x ^ n) C (pow_le_geomFiber_weight 𝕜 ν x C hx) (pow_zero x)
    (pow_add x)

variable (x : B) (C : ℝ) (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n)

theorem geomAeval_apply (a : lpOneAlg ℕ (geomFiber 𝕜 ν)) :
    geomAeval 𝕜 ν x C hx a = ∑' n, toRealSeq a n • x ^ n := rfl

theorem geomAeval_toContinuousLinearMap :
    (geomAeval 𝕜 ν x C hx).toContinuousLinearMap
      = liftCLM (fun n => x ^ n) C (pow_le_geomFiber_weight 𝕜 ν x C hx) := rfl

/-- Computation face on every single: `eₙ ↦ xⁿ`. -/
@[simp] theorem geomAeval_single (n : ℕ) :
    geomAeval 𝕜 ν x C hx (single n 1) = x ^ n :=
  liftAlgHom_single _ _ _ _ _ n

/-- Computation face on the generator: `e₁ ↦ x`. -/
@[simp] theorem geomAeval_gen : geomAeval 𝕜 ν x C hx (single 1 1) = x := by
  rw [geomAeval_single, pow_one]

/-- Pointwise norm bound: `‖geomAeval 𝕜 ν x C hx a‖ ≤ C ‖a‖`. -/
theorem norm_geomAeval_apply_le (a : lpOneAlg ℕ (geomFiber 𝕜 ν)) :
    ‖geomAeval 𝕜 ν x C hx a‖ ≤ C * ‖a‖ :=
  norm_liftAlgHom_apply_le _ _ _ _ _ a

omit [NormedAlgebra 𝕜 B] [CompleteSpace B] in
/-- In a `NormOneClass` target, `‖x‖ ≤ ν` gives power growth at `C = 1`. -/
theorem pow_le_of_norm_le [NormOneClass B] {x : B} (hx : ‖x‖ ≤ (ν : ℝ)) (n : ℕ) :
    ‖x ^ n‖ ≤ 1 * (ν : ℝ) ^ n := by
  rw [one_mul]
  exact (norm_pow_le x n).trans (pow_le_pow_left₀ (norm_nonneg x) hx n)

/-- Evaluation at an element of norm at most `ν` (the `C = 1` case; the
`NormOneClass` hypothesis is what makes `n = 0` work). -/
def geomAeval_of_norm_le [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ)) :
    lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B :=
  geomAeval 𝕜 ν x 1 (pow_le_of_norm_le ν hx)

@[simp] theorem geomAeval_of_norm_le_gen [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ)) :
    geomAeval_of_norm_le 𝕜 ν x hx (single 1 1) = x :=
  geomAeval_gen 𝕜 ν x 1 _

/-- Contractivity of evaluation at a point of norm at most `ν`. -/
theorem norm_geomAeval_of_norm_le_apply_le [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ))
    (a : lpOneAlg ℕ (geomFiber 𝕜 ν)) :
    ‖geomAeval_of_norm_le 𝕜 ν x hx a‖ ≤ ‖a‖ := by
  have h := norm_geomAeval_apply_le 𝕜 ν x 1 (pow_le_of_norm_le ν hx) a
  rwa [one_mul] at h

end Aeval

/-! ### Uniqueness: determination on the generator -/

section Ext

variable {𝕜 : Type*} [NormedField 𝕜] (ν : PosReal)

/-- Powers of the generator are the singles: `e₁ⁿ = eₙ`. -/
theorem gen_pow_eq_single (n : ℕ) :
    (single (E := geomFiber 𝕜 ν) 1 (1 : 𝕜)) ^ n = single n 1 := by
  rw [single_pow, smul_eq_mul, mul_one]

/-- `ν` is the spectral radius of the generator: `‖e₁ⁿ‖ = νⁿ` exactly. -/
theorem norm_gen_pow (n : ℕ) :
    ‖(single (E := geomFiber 𝕜 ν) 1 (1 : 𝕜)) ^ n‖ = (ν : ℝ) ^ n := by
  rw [gen_pow_eq_single, norm_single, norm_one, one_mul, geomFiber_weight]

variable {B : Type*} [NormedRing B] [NormedAlgebra 𝕜 B]

/-- **Determination on the generator** (uniqueness face): two continuous
algebra homomorphisms out of the geometric ℓ¹ algebra agreeing on `e₁` are
equal. -/
theorem geomAlgHom_ext ⦃φ ψ : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B⦄
    (h : φ (single 1 1) = ψ (single 1 1)) : φ = ψ :=
  continuousAlgHom_ext fun n => by rw [← gen_pow_eq_single, map_pow, map_pow, h]

end Ext

/-! ### Completeness: every continuous algebra homomorphism is an evaluation -/

section Complete

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜] (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormedAlgebra 𝕜 B]

/-- The image of the generator under a continuous algebra homomorphism has
power growth at the operator norm: `‖(φ e₁)ⁿ‖ ≤ ‖φ‖ νⁿ`. -/
theorem norm_gen_pow_le (φ : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B) (n : ℕ) :
    ‖φ (single 1 1) ^ n‖ ≤ ‖φ.toContinuousLinearMap‖ * (ν : ℝ) ^ n := by
  rw [← map_pow, gen_pow_eq_single]
  have h := φ.toContinuousLinearMap.le_opNorm (single n 1)
  rwa [norm_single, norm_one, one_mul, geomFiber_weight] at h

variable [CompleteSpace B]

/-- **Every continuous algebra homomorphism is evaluation at the image of the
generator** (completeness face), at the growth constant
`‖φ.toContinuousLinearMap‖` (`ContinuousAlgHom` carries no norm of its own). -/
theorem eq_geomAeval_gen (φ : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B) :
    φ = geomAeval 𝕜 ν (φ (single 1 1)) ‖φ.toContinuousLinearMap‖ (norm_gen_pow_le ν φ) :=
  geomAlgHom_ext ν (by rw [geomAeval_gen])

/-- Existential form of `eq_geomAeval_gen`. -/
theorem exists_eq_geomAeval (φ : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B) :
    ∃ (x : B) (C : ℝ) (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n), geomAeval 𝕜 ν x C hx = φ :=
  ⟨_, _, _, (eq_geomAeval_gen ν φ).symm⟩

end Complete

/-! ### The gate: the generator value lies in the closed disc of radius `ν` -/

section Gate

variable {𝕜 : Type*} [NontriviallyNormedField 𝕜] (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormOneClass B] [NormMulClass B] [NormedAlgebra 𝕜 B]

/-- **The generator gate** (disc). When the norm of the target is
multiplicative, the image of the generator under any continuous algebra
homomorphism lies in the closed disc of radius `ν`: `‖φ e₁‖ ≤ ν`.

Multiplicativity turns the operator-norm power growth `‖(φ e₁)ⁿ‖ ≤ ‖φ‖ νⁿ`
(`norm_gen_pow_le`) into `‖φ e₁‖ⁿ ≤ ‖φ‖ νⁿ`, and the archimedean gate
`le_of_forall_pow_le_mul_pow` reads off `‖φ e₁‖ ≤ ν`. Together with
`eq_geomAeval_gen` this is the classification of the continuous characters of
the geometric ℓ¹ algebra: evaluation at a point of the closed disc. -/
theorem norm_gen_le (φ : lpOneAlg ℕ (geomFiber 𝕜 ν) →A[𝕜] B) :
    ‖φ (single 1 1)‖ ≤ (ν : ℝ) :=
  le_of_forall_pow_le_mul_pow ν.coe_pos fun n => by
    rw [← norm_pow]; exact norm_gen_pow_le ν φ n

end Gate

end lpOneAlg

/-! ### The real instance `l1Weighted ν`, and the bridge to `evalContinuousAlgHom` -/

namespace l1Weighted

section Aeval

variable (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormedAlgebra ℝ B] [CompleteSpace B]

/-- Evaluation of `l1Weighted ν` at an element of power growth
(`lpOneAlg.geomAeval` at `𝕜 = ℝ`; `l1Weighted ν = lpOneAlg ℕ (geomFiber ℝ ν)`
definitionally). -/
def aeval (x : B) (C : ℝ) (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n) :
    l1Weighted ν →A[ℝ] B :=
  lpOneAlg.geomAeval ℝ ν x C hx

variable (x : B) (C : ℝ) (hx : ∀ n, ‖x ^ n‖ ≤ C * (ν : ℝ) ^ n)

theorem aeval_apply (a : l1Weighted ν) :
    aeval ν x C hx a = ∑' n, lpOneAlg.toRealSeq a n • x ^ n := rfl

@[simp] theorem aeval_single (n : ℕ) :
    aeval ν x C hx (lpOneAlg.single n 1) = x ^ n :=
  lpOneAlg.geomAeval_single ℝ ν x C hx n

@[simp] theorem aeval_gen : aeval ν x C hx (lpOneAlg.single 1 1) = x :=
  lpOneAlg.geomAeval_gen ℝ ν x C hx

theorem norm_aeval_apply_le (a : l1Weighted ν) : ‖aeval ν x C hx a‖ ≤ C * ‖a‖ :=
  lpOneAlg.norm_geomAeval_apply_le ℝ ν x C hx a

/-- Evaluation at an element of norm at most `ν` (`C = 1`). -/
def aeval_of_norm_le [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ)) :
    l1Weighted ν →A[ℝ] B :=
  lpOneAlg.geomAeval_of_norm_le ℝ ν x hx

@[simp] theorem aeval_of_norm_le_gen [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ)) :
    aeval_of_norm_le ν x hx (lpOneAlg.single 1 1) = x :=
  lpOneAlg.geomAeval_of_norm_le_gen ℝ ν x hx

theorem norm_aeval_of_norm_le_apply_le [NormOneClass B] (x : B) (hx : ‖x‖ ≤ (ν : ℝ))
    (a : l1Weighted ν) : ‖aeval_of_norm_le ν x hx a‖ ≤ ‖a‖ :=
  lpOneAlg.norm_geomAeval_of_norm_le_apply_le ℝ ν x hx a

end Aeval

section Ext

variable (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormedAlgebra ℝ B]

/-- Determination on the generator for `l1Weighted ν`. -/
theorem algHom_ext ⦃φ ψ : l1Weighted ν →A[ℝ] B⦄
    (h : φ (lpOneAlg.single 1 1) = ψ (lpOneAlg.single 1 1)) : φ = ψ :=
  lpOneAlg.geomAlgHom_ext ν h

variable [CompleteSpace B]

/-- Every continuous ℝ-algebra homomorphism out of `l1Weighted ν` is evaluation
at the image of the generator. -/
theorem eq_aeval_gen (φ : l1Weighted ν →A[ℝ] B) :
    φ = aeval ν (φ (lpOneAlg.single 1 1)) ‖φ.toContinuousLinearMap‖
      (lpOneAlg.norm_gen_pow_le ν φ) :=
  lpOneAlg.eq_geomAeval_gen ν φ

end Ext

section Gate

variable (ν : PosReal)
variable {B : Type*} [NormedRing B] [NormOneClass B] [NormMulClass B] [NormedAlgebra ℝ B]

/-- The generator gate for `l1Weighted ν`: the image of the generator lies in
the closed disc of radius `ν`. -/
theorem norm_gen_le (φ : l1Weighted ν →A[ℝ] B) :
    ‖φ (lpOneAlg.single 1 1)‖ ≤ (ν : ℝ) :=
  lpOneAlg.norm_gen_le ν φ

end Gate

section Bridge

variable {ν : PosReal}

/-- The geometric `l1Weighted.single` is the generic `lpOneAlg.single`. -/
theorem single_eq_lpOneAlg_single (n : ℕ) (x : ℝ) :
    (l1Weighted.single n x : l1Weighted ν) = lpOneAlg.single n x := by
  apply lpOneAlg.ext_toRealSeq
  funext k
  rw [lpOneAlg.toRealSeq_single]
  exact l1Weighted.single_toSeq n k x

/-- The library's pointwise evaluation sends the generator to the point. -/
theorem evalContinuousAlgHom_gen (z : ℝ) (hz : |z| ≤ ν) :
    l1Weighted.evalContinuousAlgHom z hz (lpOneAlg.single 1 1) = z := by
  rw [l1Weighted.evalContinuousAlgHom_apply, ← single_eq_lpOneAlg_single,
    l1Weighted.eval_single, one_mul, pow_one]

/-- **Bridge**: the library's pointwise evaluation `evalContinuousAlgHom z hz`
(Evaluation.lean, multiplicativity by Mertens) is the `C = 1` evaluation of
the `aeval` API — by uniqueness on the generator alone. -/
theorem aeval_eq_evalContinuousAlgHom (z : ℝ) (hz : |z| ≤ ν) :
    aeval_of_norm_le ν z hz = l1Weighted.evalContinuousAlgHom z hz :=
  algHom_ext ν (by rw [aeval_of_norm_le_gen, evalContinuousAlgHom_gen])

end Bridge

end l1Weighted

end RadiiPolynomial

end
